[main]
Version=5.000
StatManager Version=5.000
Report Version=5.000
Schedule Assistent Version=6.000
TemplateCreatedVersion=Version 9.0.0.118.00  Supports 128 bit SSL
TemplateLastSavedVersion=Version 9.0.0.118.00  Supports 128 bit SSL 
Agendas=NectarToolbar_Polling;Toolbar;NectarToolbar_EXE_download;
[NectarToolbar_Polling]
Path=C:\PerformanceTesting\Projects\STD_TESTSCRIPTS\Toolbar\NectarToolbar_Polling.wlp
ExecutionType=0
IsMix=0
Schedule_1=0
From_1=00000000
To_1=00003000
LoadSize_1=0
AssistentItemAAString_1=8 '11 RunLoadTime '3 180 '13 StartLoadSize '1 5 '12 RumpDownTime '1 1 '16 AssistantCaption '22 Ramp Up Schedule Model '13 ScheduleModel '1 6 '11 RunLoadSize '2 10 '10 RumpUpTime '1 5 '9 TotalTime '3 186
Schedule_2=1
From_2=00003000
To_2=00003030
LoadSize_2=5
Schedule_3=1
From_3=00003030
To_3=00003100
LoadSize_3=5
Schedule_4=1
From_4=00003100
To_4=00003130
LoadSize_4=6
Schedule_5=1
From_5=00003130
To_5=00003200
LoadSize_5=6
Schedule_6=1
From_6=00003200
To_6=00003230
LoadSize_6=7
Schedule_7=1
From_7=00003230
To_7=00003300
LoadSize_7=7
Schedule_8=1
From_8=00003300
To_8=00003330
LoadSize_8=8
Schedule_9=1
From_9=00003330
To_9=00003400
LoadSize_9=8
Schedule_10=1
From_10=00003400
To_10=00003430
LoadSize_10=9
Schedule_11=1
From_11=00003430
To_11=00003500
LoadSize_11=9
Schedule_12=1
From_12=00003500
To_12=00033500
LoadSize_12=10
Schedule_13=1
From_13=00033500
To_13=00033530
LoadSize_13=7
Schedule_14=1
From_14=00033530
To_14=00033600
LoadSize_14=5
LoadMachines=10.1.2.5;10.1.2.6;
[NectarToolbar_Polling : Browser Emulation]
IsMultiThreadVirtualClientPC=1
IsMultiThreadVirtualClientLG=0
MultiThreadVirtualClientPCNum=4
MultiThreadVirtualClientLGNum=1
BrowserCachePC=0
BrowserCacheLG=1
DNSCachePC=1
DNSCacheLG=1
SSLCachePC=1
SSLCacheLG=1
HTTPVersion=1
KeepAlivePC=1
KeepAliveLG=1
RedirectionEnabled=1
RedirectionLimit=10
Browser types list=Microsoft Internet Explorer;Mozilla Firefox;Chrome;Safari;Opera;iPhone;Android Webkit Browser;BlackBerry;Opera Mini;S60 Nokia Browser;Unix/Linux;WAP;Default;
Microsoft Internet Explorer=0|Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 7.1; Trident/5.0)|Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET CLR 1.0.3705; .NET CLR 1.1.4322)|Mozilla/5.0 (Windows; U; MSIE 7.0; Windows NT 6.0; en-US)|
Mozilla Firefox=0|Mozilla/5.0 (X11; Linux i686; rv:6.0) Gecko/20100101 Firefox/6.0|Mozilla/5.0 (Windows NT 6.1; WOW64; rv:5.0) Gecko/20100101 Firefox/5.0|Mozilla/5.0 (Windows NT 6.1; rv:1.9) Gecko/20100101 Firefox/4.0|
Chrome=0|Mozilla/5.0 (Windows NT 5.1) AppleWebKit/535.6 (KHTML, like Gecko) Chrome/16.0.897.0 Safari/535.6|
Safari=0|Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_8; de-at) AppleWebKit/533.21.1 (KHTML, like Gecko) Version/5.0.5 Safari/533.21.1|
Opera=0|Opera/9.80 (Windows NT 6.1; U; es-ES) Presto/2.9.181 Version/12.00|
iPhone=0|Mozilla/5.0 (iPhone; CPU iPhone OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A334 Safari/7534.48.3|
Android Webkit Browser=0|Mozilla/5.0 (Linux; U; Android 2.3.5; en-us; HTC Vision Build/GRI40) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1|
BlackBerry=0|Mozilla/5.0 (BlackBerry; U; BlackBerry 9850; en-US) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.0.0.115 Mobile Safari/534.11+|
Opera Mini=0|Opera/9.80 (J2ME/MIDP; Opera Mini/9.80 (S60; SymbOS; Opera Mobi/23.348; U; en) Presto/2.5.25 Version/10.54|
S60 Nokia Browser=0|NokiaN97i/SymbianOS/9.1 Series60/3.0|
Unix/Linux=0|Lynx/2.6 libwww-FM/2.14|Mozilla/4.04[en](X11;I;Linux 2.0.33 i586)|
WAP=0|Alcatel OneTouch|Generic digital phone|Mitsubishi MobileAccess|Samsung Duette|Motorola i1000plus|
Default=0|Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0)|
Selected Browser Type=Default
Selected User Agent=Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)
SSL Cypher Suite=None
SSL Cypher Suite Enabled=0
Encoding Value=0
EnforceEncoding=0
bGZipSupport=0
[NectarToolbar_Polling : Authentication]
UserName=
PassWord=
NTUserName=
NTUserPassword=
KerberosServer=
AuthType=0
ProxyUserName=
ProxyPassWord=
SSLClientCertificateFile=
SSLClientCertificatePassword=
ProxyHost=
ProxyPort=
[NectarToolbar_Polling : Options\Connection]
Speed for LG=
Speed for PC=
Is Compression Rate for LG=0
Is Compression Rate for PC=0
Is Speed for LG=0
Is Speed for PC=0
Compression Rate for LG( in )=0
Compression Rate for LG( out )=0
Compression Rate for PC( out )=0
Compression Rate for PC( in )=0
[NectarToolbar_Polling : Diagnostic]
Start Round=1
End Round=1
Output Dir=
Syntax Check=0
Log Check=0
Trace Check=0
Automatic State=0
SaveCSJS Check=0
CSJSDiagnosticMessages Check=0
[NectarToolbar_Polling : FunctionalTesting]
Transaction Failed=0
Failed Time=20
Verification Portion=2
Severity=2
Automatic Transaction=0
Verification=0
Object Level=0
HTTP Level=0
sTextSearch=
nCompareTitle=0
nFramesNumber=0
nTextSearch=0
nCompareLinks=0
nCompareForms=0
nCompareImages=0
nCompareTables=0
[NectarToolbar_Polling : ClientType]
clientType=5
getImages=1
UseClientJSFull=1
UseClientJSOptim=0
JavaFull=0
JavaOptimized=0
[NectarToolbar_Polling : PassFailDefinition]
definitionType=1
checkErrors=0
checkSevere=1
checkStopTest=0
checkWarnings=0
errorNum=5
ruleCheck=15
warningNum=15
[NectarToolbar_Polling : SleepTimeControl]
sleepControlType=1
timeBetween=2
timeAnd=10
deviationPersent=10
[NectarToolbar_Polling : BrowserDialogs]
BrowserDialogsOptions=<IE_OPTIONS Option_version=\"19\">\r\n\t<IE_DIALOG name=\"Alert\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Confirm\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Prompt\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Input\"></field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Print\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Cookie_IE6\">\r\n\t\t<Answer>\r\n\t\t\t<value>Allow</value>\r\n\t\t\t<value>Block</value>\r\n\t\t\t<default>Allow</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"ApplyToAll\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Cookie\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FormSubmit\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FormResubmit\">\r\n\t\t<Answer>\r\n\t\t\t<value>Retry</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Retry</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SwitchNonSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SwitchSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"NonSecureOnSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientAuthentication\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"string\" name=\"Domain\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ConnectToMS_WinXP\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Email\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"checkbox\" name=\"AutoSignIn\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientAuthentication_WinXP\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientCertificate\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Certificate\">\r\n\t\t\t<default>0</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"HostCertificate\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload_IE6\">\r\n\t\t<Answer>\r\n\t\t\t<value>Open</value>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload_IE6_XP\">\r\n\t\t<Answer>\r\n\t\t\t<value>Open</value>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SaveFile\">\r\n\t\t<Answer>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"FileName\"></field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SaveFileConfirmation\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ActiveXInstall\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysTrust\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"RunActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"UnsafeActiveX\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ScriptAccessingActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"NavigateSubFrames\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ActiveScripting\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"JavaScripting\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Redirection\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"AutoComplete\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"RememberPassword\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"DoNotOffer\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FtpAuthentication\">\r\n\t\t<Answer>\r\n\t\t\t<value>Login</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Login</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Server\"></field>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"string\" name=\"Email\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Anonymous\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FtpFolderError\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"DocumentModified\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"JavascriptError\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"WindowClosing\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SuspiciousActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Reboot\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"YesNoCancel\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"YesNo\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"OkCancel\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Ok\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n</IE_OPTIONS>
[NectarToolbar_Polling : EmulationPlayback]
useHistory=0
historyLimit=1
csjsRecovery=1
[NectarToolbar_Polling : Java]
strSelectedJVM=Default
[NectarToolbar_Polling : WebServices]
sBasicPassword=
sUserName=
sProxyHost=
sProxyPassword=
sProxyUser=
sProxyPort=
nWSClientType=1
[NectarToolbar_Polling : ResetMechanism]
bResetEnable=0
nCreateLGRetryTimes=3
nLGTimeout=150
nResetTimeout=60
nStopLGTimeout=3
[NectarToolbar_Polling : HTTPParameters]
bHTTPVersion=1
bMultiIPSupport=0
bEncodeFormData=1
bAcceptLanguage=0
StrAcceptLanguage=
[NectarToolbar_Polling : BrowserCache]
bFilterApplets=1
bFilterImages=1
bFilterJSFiles=1
bFilterStyleSheets=1
bFilterXMLFiles=1
bFilterDynamic=0
nCacheType=3
bFilterAppletsPC=1
bFilterImagesPC=1
bFilterJSFilesPC=1
bFilterStyleSheetsPC=1
bFilterXMLFilesPC=1
bFilterDynamicPC=0
nCacheTypePC=3
[NectarToolbar_Polling@10.1.2.5]
StationType=PC
OperatingSystem=NT
ClientType=2
Type=Emulation
Schedule_1=0
From_1=00000000
To_1=00003000
LoadSize_1=0
AssistentItemAAString_1=8 '11 RunLoadTime '3 180 '13 StartLoadSize '1 3 '12 RumpDownTime '1 1 '16 AssistantCaption '22 Ramp Up Schedule Model '13 ScheduleModel '1 6 '11 RunLoadSize '1 5 '10 RumpUpTime '1 5 '9 TotalTime '3 186
Schedule_2=1
From_2=00003000
To_2=00003030
LoadSize_2=3
Schedule_3=1
From_3=00003030
To_3=00003100
LoadSize_3=3
Schedule_4=1
From_4=00003100
To_4=00003130
LoadSize_4=3
Schedule_5=1
From_5=00003130
To_5=00003200
LoadSize_5=3
Schedule_6=1
From_6=00003200
To_6=00003230
LoadSize_6=4
Schedule_7=1
From_7=00003230
To_7=00003300
LoadSize_7=4
Schedule_8=1
From_8=00003300
To_8=00003330
LoadSize_8=4
Schedule_9=1
From_9=00003330
To_9=00003400
LoadSize_9=4
Schedule_10=1
From_10=00003400
To_10=00003430
LoadSize_10=5
Schedule_11=1
From_11=00003430
To_11=00003500
LoadSize_11=5
Schedule_12=1
From_12=00003500
To_12=00033500
LoadSize_12=5
Schedule_13=1
From_13=00033500
To_13=00033530
LoadSize_13=4
Schedule_14=1
From_14=00033530
To_14=00033600
LoadSize_14=3
[NectarToolbar_Polling@10.1.2.6]
StationType=PC
OperatingSystem=NT
ClientType=2
Type=Emulation
Schedule_1=0
From_1=00000000
To_1=00003000
LoadSize_1=0
AssistentItemAAString_1=8 '11 RunLoadTime '3 180 '13 StartLoadSize '1 2 '12 RumpDownTime '1 1 '16 AssistantCaption '22 Ramp Up Schedule Model '13 ScheduleModel '1 6 '11 RunLoadSize '1 5 '10 RumpUpTime '1 5 '9 TotalTime '3 186
Schedule_2=1
From_2=00003000
To_2=00003030
LoadSize_2=2
Schedule_3=1
From_3=00003030
To_3=00003100
LoadSize_3=2
Schedule_4=1
From_4=00003100
To_4=00003130
LoadSize_4=3
Schedule_5=1
From_5=00003130
To_5=00003200
LoadSize_5=3
Schedule_6=1
From_6=00003200
To_6=00003230
LoadSize_6=3
Schedule_7=1
From_7=00003230
To_7=00003300
LoadSize_7=3
Schedule_8=1
From_8=00003300
To_8=00003330
LoadSize_8=4
Schedule_9=1
From_9=00003330
To_9=00003400
LoadSize_9=4
Schedule_10=1
From_10=00003400
To_10=00003430
LoadSize_10=4
Schedule_11=1
From_11=00003430
To_11=00003500
LoadSize_11=4
Schedule_12=1
From_12=00003500
To_12=00033500
LoadSize_12=5
Schedule_13=1
From_13=00033500
To_13=00033530
LoadSize_13=3
Schedule_14=1
From_14=00033530
To_14=00033600
LoadSize_14=2
[Toolbar]
Path=C:\PerformanceTesting\Projects\STD_MIX\Toolbar\Toolbar.mix
ExecutionType=0
IsMix=1
AssistentItemAAString_1=8 '11 RunLoadTime '3 180 '13 StartLoadSize '1 5 '12 RumpDownTime '1 1 '16 AssistantCaption '22 Ramp Up Schedule Model '13 ScheduleModel '1 6 '11 RunLoadSize '2 15 '10 RumpUpTime '1 5 '9 TotalTime '3 186
Schedule_1=1
From_1=00000000
To_1=00000030
LoadSize_1=5
Schedule_2=1
From_2=00000030
To_2=00000100
LoadSize_2=6
Schedule_3=1
From_3=00000100
To_3=00000130
LoadSize_3=7
Schedule_4=1
From_4=00000130
To_4=00000200
LoadSize_4=8
Schedule_5=1
From_5=00000200
To_5=00000230
LoadSize_5=9
Schedule_6=1
From_6=00000230
To_6=00000300
LoadSize_6=10
Schedule_7=1
From_7=00000300
To_7=00000330
LoadSize_7=11
Schedule_8=1
From_8=00000330
To_8=00000400
LoadSize_8=12
Schedule_9=1
From_9=00000400
To_9=00000430
LoadSize_9=13
Schedule_10=1
From_10=00000430
To_10=00000500
LoadSize_10=14
Schedule_11=1
From_11=00000500
To_11=00030500
LoadSize_11=15
Schedule_12=1
From_12=00030500
To_12=00030530
LoadSize_12=10
Schedule_13=1
From_13=00030530
To_13=00030600
LoadSize_13=5
LoadMachines=10.1.2.5;10.1.2.6;
[Mix::NectarToolbar_Search : Browser Emulation]
IsMultiThreadVirtualClientPC=1
IsMultiThreadVirtualClientLG=0
MultiThreadVirtualClientPCNum=4
MultiThreadVirtualClientLGNum=1
BrowserCachePC=0
BrowserCacheLG=1
DNSCachePC=1
DNSCacheLG=1
SSLCachePC=1
SSLCacheLG=1
HTTPVersion=1
KeepAlivePC=1
KeepAliveLG=1
RedirectionEnabled=1
RedirectionLimit=10
Browser types list=Microsoft Internet Explorer;Mozilla Firefox;Chrome;Safari;Opera;iPhone;Android Webkit Browser;BlackBerry;Opera Mini;S60 Nokia Browser;Unix/Linux;WAP;Default;
Microsoft Internet Explorer=0|Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 7.1; Trident/5.0)|Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET CLR 1.0.3705; .NET CLR 1.1.4322)|Mozilla/5.0 (Windows; U; MSIE 7.0; Windows NT 6.0; en-US)|
Mozilla Firefox=0|Mozilla/5.0 (X11; Linux i686; rv:6.0) Gecko/20100101 Firefox/6.0|Mozilla/5.0 (Windows NT 6.1; WOW64; rv:5.0) Gecko/20100101 Firefox/5.0|Mozilla/5.0 (Windows NT 6.1; rv:1.9) Gecko/20100101 Firefox/4.0|
Chrome=0|Mozilla/5.0 (Windows NT 5.1) AppleWebKit/535.6 (KHTML, like Gecko) Chrome/16.0.897.0 Safari/535.6|
Safari=0|Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_8; de-at) AppleWebKit/533.21.1 (KHTML, like Gecko) Version/5.0.5 Safari/533.21.1|
Opera=0|Opera/9.80 (Windows NT 6.1; U; es-ES) Presto/2.9.181 Version/12.00|
iPhone=0|Mozilla/5.0 (iPhone; CPU iPhone OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A334 Safari/7534.48.3|
Android Webkit Browser=0|Mozilla/5.0 (Linux; U; Android 2.3.5; en-us; HTC Vision Build/GRI40) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1|
BlackBerry=0|Mozilla/5.0 (BlackBerry; U; BlackBerry 9850; en-US) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.0.0.115 Mobile Safari/534.11+|
Opera Mini=0|Opera/9.80 (J2ME/MIDP; Opera Mini/9.80 (S60; SymbOS; Opera Mobi/23.348; U; en) Presto/2.5.25 Version/10.54|
S60 Nokia Browser=0|NokiaN97i/SymbianOS/9.1 Series60/3.0|
Unix/Linux=0|Lynx/2.6 libwww-FM/2.14|Mozilla/4.04[en](X11;I;Linux 2.0.33 i586)|
WAP=0|Alcatel OneTouch|Generic digital phone|Mitsubishi MobileAccess|Samsung Duette|Motorola i1000plus|
Default=0|Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0)|
Selected Browser Type=Default
Selected User Agent=Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)
SSL Cypher Suite=None
SSL Cypher Suite Enabled=0
Encoding Value=0
EnforceEncoding=0
bGZipSupport=0
[Mix::NectarToolbar_Search : Authentication]
UserName=
PassWord=
NTUserName=
NTUserPassword=
KerberosServer=
AuthType=0
ProxyUserName=
ProxyPassWord=
SSLClientCertificateFile=
SSLClientCertificatePassword=
ProxyHost=
ProxyPort=
[Mix::NectarToolbar_Search : Options\Connection]
Speed for LG=
Speed for PC=
Is Compression Rate for LG=0
Is Compression Rate for PC=0
Is Speed for LG=0
Is Speed for PC=0
Compression Rate for LG( in )=0
Compression Rate for LG( out )=0
Compression Rate for PC( out )=0
Compression Rate for PC( in )=0
[Mix::NectarToolbar_Search : Diagnostic]
Start Round=1
End Round=1
Output Dir=
Syntax Check=0
Log Check=0
Trace Check=0
Automatic State=0
SaveCSJS Check=0
CSJSDiagnosticMessages Check=0
[Mix::NectarToolbar_Search : FunctionalTesting]
Transaction Failed=0
Failed Time=20
Verification Portion=2
Severity=2
Automatic Transaction=0
Verification=0
Object Level=0
HTTP Level=0
sTextSearch=
nCompareTitle=0
nFramesNumber=0
nTextSearch=0
nCompareLinks=0
nCompareForms=0
nCompareImages=0
nCompareTables=0
[Mix::NectarToolbar_Search : ClientType]
clientType=5
getImages=1
UseClientJSFull=1
UseClientJSOptim=0
JavaFull=0
JavaOptimized=0
[Mix::NectarToolbar_Search : PassFailDefinition]
definitionType=1
checkErrors=0
checkSevere=1
checkStopTest=0
checkWarnings=0
errorNum=5
ruleCheck=15
warningNum=15
[Mix::NectarToolbar_Search : SleepTimeControl]
sleepControlType=1
timeBetween=2
timeAnd=10
deviationPersent=10
[Mix::NectarToolbar_Search : BrowserDialogs]
BrowserDialogsOptions=<IE_OPTIONS Option_version=\"19\">\r\n\t<IE_DIALOG name=\"Alert\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Confirm\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Prompt\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Input\"></field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Print\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Cookie_IE6\">\r\n\t\t<Answer>\r\n\t\t\t<value>Allow</value>\r\n\t\t\t<value>Block</value>\r\n\t\t\t<default>Allow</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"ApplyToAll\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Cookie\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FormSubmit\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FormResubmit\">\r\n\t\t<Answer>\r\n\t\t\t<value>Retry</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Retry</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SwitchNonSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SwitchSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"NonSecureOnSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientAuthentication\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"string\" name=\"Domain\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ConnectToMS_WinXP\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Email\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"checkbox\" name=\"AutoSignIn\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientAuthentication_WinXP\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientCertificate\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Certificate\">\r\n\t\t\t<default>0</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"HostCertificate\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload_IE6\">\r\n\t\t<Answer>\r\n\t\t\t<value>Open</value>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload_IE6_XP\">\r\n\t\t<Answer>\r\n\t\t\t<value>Open</value>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SaveFile\">\r\n\t\t<Answer>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"FileName\"></field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SaveFileConfirmation\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ActiveXInstall\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysTrust\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"RunActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"UnsafeActiveX\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ScriptAccessingActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"NavigateSubFrames\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ActiveScripting\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"JavaScripting\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Redirection\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"AutoComplete\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"RememberPassword\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"DoNotOffer\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FtpAuthentication\">\r\n\t\t<Answer>\r\n\t\t\t<value>Login</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Login</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Server\"></field>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"string\" name=\"Email\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Anonymous\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FtpFolderError\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"DocumentModified\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"JavascriptError\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"WindowClosing\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SuspiciousActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Reboot\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"YesNoCancel\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"YesNo\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"OkCancel\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Ok\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n</IE_OPTIONS>
[Mix::NectarToolbar_Search : EmulationPlayback]
useHistory=0
historyLimit=1
csjsRecovery=1
[Mix::NectarToolbar_Search : Java]
strSelectedJVM=Default
[Mix::NectarToolbar_Search : WebServices]
sBasicPassword=
sUserName=
sProxyHost=
sProxyPassword=
sProxyUser=
sProxyPort=
nWSClientType=1
[Mix::NectarToolbar_Search : ResetMechanism]
bResetEnable=0
nCreateLGRetryTimes=3
nLGTimeout=150
nResetTimeout=60
nStopLGTimeout=3
[Mix::NectarToolbar_Search : HTTPParameters]
bHTTPVersion=1
bMultiIPSupport=0
bEncodeFormData=1
bAcceptLanguage=0
StrAcceptLanguage=
[Mix::NectarToolbar_Search : BrowserCache]
bFilterApplets=1
bFilterImages=1
bFilterJSFiles=1
bFilterStyleSheets=1
bFilterXMLFiles=1
bFilterDynamic=0
nCacheType=3
bFilterAppletsPC=1
bFilterImagesPC=1
bFilterJSFilesPC=1
bFilterStyleSheetsPC=1
bFilterXMLFilesPC=1
bFilterDynamicPC=0
nCacheTypePC=3
[Mix::NectarToolbar_INSTALL_UNINSTALL : Browser Emulation]
IsMultiThreadVirtualClientPC=1
IsMultiThreadVirtualClientLG=0
MultiThreadVirtualClientPCNum=4
MultiThreadVirtualClientLGNum=1
BrowserCachePC=0
BrowserCacheLG=1
DNSCachePC=1
DNSCacheLG=1
SSLCachePC=1
SSLCacheLG=1
HTTPVersion=1
KeepAlivePC=1
KeepAliveLG=1
RedirectionEnabled=1
RedirectionLimit=10
Browser types list=Microsoft Internet Explorer;Mozilla Firefox;Chrome;Safari;Opera;iPhone;Android Webkit Browser;BlackBerry;Opera Mini;S60 Nokia Browser;Unix/Linux;WAP;Default;
Microsoft Internet Explorer=0|Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 7.1; Trident/5.0)|Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET CLR 1.0.3705; .NET CLR 1.1.4322)|Mozilla/5.0 (Windows; U; MSIE 7.0; Windows NT 6.0; en-US)|
Mozilla Firefox=0|Mozilla/5.0 (X11; Linux i686; rv:6.0) Gecko/20100101 Firefox/6.0|Mozilla/5.0 (Windows NT 6.1; WOW64; rv:5.0) Gecko/20100101 Firefox/5.0|Mozilla/5.0 (Windows NT 6.1; rv:1.9) Gecko/20100101 Firefox/4.0|
Chrome=0|Mozilla/5.0 (Windows NT 5.1) AppleWebKit/535.6 (KHTML, like Gecko) Chrome/16.0.897.0 Safari/535.6|
Safari=0|Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_8; de-at) AppleWebKit/533.21.1 (KHTML, like Gecko) Version/5.0.5 Safari/533.21.1|
Opera=0|Opera/9.80 (Windows NT 6.1; U; es-ES) Presto/2.9.181 Version/12.00|
iPhone=0|Mozilla/5.0 (iPhone; CPU iPhone OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A334 Safari/7534.48.3|
Android Webkit Browser=0|Mozilla/5.0 (Linux; U; Android 2.3.5; en-us; HTC Vision Build/GRI40) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1|
BlackBerry=0|Mozilla/5.0 (BlackBerry; U; BlackBerry 9850; en-US) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.0.0.115 Mobile Safari/534.11+|
Opera Mini=0|Opera/9.80 (J2ME/MIDP; Opera Mini/9.80 (S60; SymbOS; Opera Mobi/23.348; U; en) Presto/2.5.25 Version/10.54|
S60 Nokia Browser=0|NokiaN97i/SymbianOS/9.1 Series60/3.0|
Unix/Linux=0|Lynx/2.6 libwww-FM/2.14|Mozilla/4.04[en](X11;I;Linux 2.0.33 i586)|
WAP=0|Alcatel OneTouch|Generic digital phone|Mitsubishi MobileAccess|Samsung Duette|Motorola i1000plus|
Default=0|Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0)|
Selected Browser Type=Default
Selected User Agent=Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)
SSL Cypher Suite=None
SSL Cypher Suite Enabled=0
Encoding Value=0
EnforceEncoding=0
bGZipSupport=0
[Mix::NectarToolbar_INSTALL_UNINSTALL : Authentication]
UserName=
PassWord=
NTUserName=
NTUserPassword=
KerberosServer=
AuthType=0
ProxyUserName=
ProxyPassWord=
SSLClientCertificateFile=
SSLClientCertificatePassword=
ProxyHost=
ProxyPort=
[Mix::NectarToolbar_INSTALL_UNINSTALL : Options\Connection]
Speed for LG=
Speed for PC=
Is Compression Rate for LG=0
Is Compression Rate for PC=0
Is Speed for LG=0
Is Speed for PC=0
Compression Rate for LG( in )=0
Compression Rate for LG( out )=0
Compression Rate for PC( out )=0
Compression Rate for PC( in )=0
[Mix::NectarToolbar_INSTALL_UNINSTALL : Diagnostic]
Start Round=1
End Round=1
Output Dir=
Syntax Check=0
Log Check=0
Trace Check=0
Automatic State=0
SaveCSJS Check=0
CSJSDiagnosticMessages Check=0
[Mix::NectarToolbar_INSTALL_UNINSTALL : FunctionalTesting]
Transaction Failed=0
Failed Time=20
Verification Portion=2
Severity=2
Automatic Transaction=0
Verification=0
Object Level=0
HTTP Level=0
sTextSearch=
nCompareTitle=0
nFramesNumber=0
nTextSearch=0
nCompareLinks=0
nCompareForms=0
nCompareImages=0
nCompareTables=0
[Mix::NectarToolbar_INSTALL_UNINSTALL : ClientType]
clientType=5
getImages=1
UseClientJSFull=1
UseClientJSOptim=0
JavaFull=0
JavaOptimized=0
[Mix::NectarToolbar_INSTALL_UNINSTALL : PassFailDefinition]
definitionType=1
checkErrors=0
checkSevere=1
checkStopTest=0
checkWarnings=0
errorNum=5
ruleCheck=15
warningNum=15
[Mix::NectarToolbar_INSTALL_UNINSTALL : SleepTimeControl]
sleepControlType=1
timeBetween=2
timeAnd=10
deviationPersent=10
[Mix::NectarToolbar_INSTALL_UNINSTALL : BrowserDialogs]
BrowserDialogsOptions=<IE_OPTIONS Option_version=\"19\">\r\n\t<IE_DIALOG name=\"Alert\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Confirm\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Prompt\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Input\"></field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Print\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Cookie_IE6\">\r\n\t\t<Answer>\r\n\t\t\t<value>Allow</value>\r\n\t\t\t<value>Block</value>\r\n\t\t\t<default>Allow</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"ApplyToAll\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Cookie\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FormSubmit\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FormResubmit\">\r\n\t\t<Answer>\r\n\t\t\t<value>Retry</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Retry</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SwitchNonSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SwitchSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"NonSecureOnSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientAuthentication\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"string\" name=\"Domain\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ConnectToMS_WinXP\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Email\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"checkbox\" name=\"AutoSignIn\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientAuthentication_WinXP\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientCertificate\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Certificate\">\r\n\t\t\t<default>0</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"HostCertificate\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload_IE6\">\r\n\t\t<Answer>\r\n\t\t\t<value>Open</value>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload_IE6_XP\">\r\n\t\t<Answer>\r\n\t\t\t<value>Open</value>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SaveFile\">\r\n\t\t<Answer>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"FileName\"></field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SaveFileConfirmation\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ActiveXInstall\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysTrust\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"RunActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"UnsafeActiveX\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ScriptAccessingActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"NavigateSubFrames\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ActiveScripting\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"JavaScripting\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Redirection\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"AutoComplete\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"RememberPassword\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"DoNotOffer\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FtpAuthentication\">\r\n\t\t<Answer>\r\n\t\t\t<value>Login</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Login</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Server\"></field>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"string\" name=\"Email\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Anonymous\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FtpFolderError\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"DocumentModified\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"JavascriptError\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"WindowClosing\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SuspiciousActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Reboot\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"YesNoCancel\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"YesNo\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"OkCancel\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Ok\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n</IE_OPTIONS>
[Mix::NectarToolbar_INSTALL_UNINSTALL : EmulationPlayback]
useHistory=0
historyLimit=1
csjsRecovery=1
[Mix::NectarToolbar_INSTALL_UNINSTALL : Java]
strSelectedJVM=Default
[Mix::NectarToolbar_INSTALL_UNINSTALL : WebServices]
sBasicPassword=
sUserName=
sProxyHost=
sProxyPassword=
sProxyUser=
sProxyPort=
nWSClientType=1
[Mix::NectarToolbar_INSTALL_UNINSTALL : ResetMechanism]
bResetEnable=0
nCreateLGRetryTimes=3
nLGTimeout=150
nResetTimeout=60
nStopLGTimeout=3
[Mix::NectarToolbar_INSTALL_UNINSTALL : HTTPParameters]
bHTTPVersion=1
bMultiIPSupport=0
bEncodeFormData=1
bAcceptLanguage=0
StrAcceptLanguage=
[Mix::NectarToolbar_INSTALL_UNINSTALL : BrowserCache]
bFilterApplets=1
bFilterImages=1
bFilterJSFiles=1
bFilterStyleSheets=1
bFilterXMLFiles=1
bFilterDynamic=0
nCacheType=3
bFilterAppletsPC=1
bFilterImagesPC=1
bFilterJSFilesPC=1
bFilterStyleSheetsPC=1
bFilterXMLFilesPC=1
bFilterDynamicPC=0
nCacheTypePC=3
[Toolbar@10.1.2.5]
StationType=PC
OperatingSystem=NT
ClientType=2
Type=Emulation
AssistentItemAAString_1=8 '11 RunLoadTime '3 180 '13 StartLoadSize '1 3 '12 RumpDownTime '1 1 '16 AssistantCaption '22 Ramp Up Schedule Model '13 ScheduleModel '1 6 '11 RunLoadSize '2 20 '10 RumpUpTime '1 5 '9 TotalTime '3 186
Schedule_1=1
From_1=00000000
To_1=00000030
LoadSize_1=3
Schedule_2=1
From_2=00000030
To_2=00000100
LoadSize_2=4
Schedule_3=1
From_3=00000100
To_3=00000130
LoadSize_3=6
Schedule_4=1
From_4=00000130
To_4=00000200
LoadSize_4=8
Schedule_5=1
From_5=00000200
To_5=00000230
LoadSize_5=9
Schedule_6=1
From_6=00000230
To_6=00000300
LoadSize_6=11
Schedule_7=1
From_7=00000300
To_7=00000330
LoadSize_7=13
Schedule_8=1
From_8=00000330
To_8=00000400
LoadSize_8=14
Schedule_9=1
From_9=00000400
To_9=00000430
LoadSize_9=16
Schedule_10=1
From_10=00000430
To_10=00000500
LoadSize_10=18
Schedule_11=1
From_11=00000500
To_11=00030500
LoadSize_11=20
Schedule_12=1
From_12=00030500
To_12=00030530
LoadSize_12=11
Schedule_13=1
From_13=00030530
To_13=00030600
LoadSize_13=3
[Toolbar@10.1.2.6]
StationType=PC
OperatingSystem=NT
ClientType=2
Type=Emulation
AssistentItemAAString_1=8 '11 RunLoadTime '3 180 '13 StartLoadSize '1 3 '12 RumpDownTime '1 1 '16 AssistantCaption '22 Ramp Up Schedule Model '13 ScheduleModel '1 6 '11 RunLoadSize '2 20 '10 RumpUpTime '1 5 '9 TotalTime '3 186
Schedule_1=1
From_1=00000000
To_1=00000030
LoadSize_1=3
Schedule_2=1
From_2=00000030
To_2=00000100
LoadSize_2=4
Schedule_3=1
From_3=00000100
To_3=00000130
LoadSize_3=6
Schedule_4=1
From_4=00000130
To_4=00000200
LoadSize_4=8
Schedule_5=1
From_5=00000200
To_5=00000230
LoadSize_5=9
Schedule_6=1
From_6=00000230
To_6=00000300
LoadSize_6=11
Schedule_7=1
From_7=00000300
To_7=00000330
LoadSize_7=13
Schedule_8=1
From_8=00000330
To_8=00000400
LoadSize_8=14
Schedule_9=1
From_9=00000400
To_9=00000430
LoadSize_9=16
Schedule_10=1
From_10=00000430
To_10=00000500
LoadSize_10=18
Schedule_11=1
From_11=00000500
To_11=00030500
LoadSize_11=20
Schedule_12=1
From_12=00030500
To_12=00030530
LoadSize_12=11
Schedule_13=1
From_13=00030530
To_13=00030600
LoadSize_13=3
[NectarToolbar_EXE_download]
Path=C:\PerformanceTesting\Projects\STD_TESTSCRIPTS\Toolbar\NectarToolbar_EXE_download.wlp
ExecutionType=0
IsMix=0
AssistentItemAAString_1=8 '11 RunLoadTime '3 180 '13 StartLoadSize '1 5 '12 RumpDownTime '1 1 '16 AssistantCaption '22 Ramp Up Schedule Model '13 ScheduleModel '1 6 '11 RunLoadSize '1 5 '10 RumpUpTime '1 2 '9 TotalTime '3 183
Schedule_1=1
From_1=00000000
To_1=00000030
LoadSize_1=5
Schedule_2=1
From_2=00000030
To_2=00000100
LoadSize_2=5
Schedule_3=1
From_3=00000100
To_3=00000130
LoadSize_3=5
Schedule_4=1
From_4=00000130
To_4=00000200
LoadSize_4=5
Schedule_5=1
From_5=00000200
To_5=00030200
LoadSize_5=5
Schedule_6=1
From_6=00030200
To_6=00030230
LoadSize_6=5
Schedule_7=1
From_7=00030230
To_7=00030300
LoadSize_7=5
LoadMachines=10.1.2.6;10.1.2.5;
[NectarToolbar_EXE_download : Browser Emulation]
IsMultiThreadVirtualClientPC=1
IsMultiThreadVirtualClientLG=0
MultiThreadVirtualClientPCNum=4
MultiThreadVirtualClientLGNum=1
BrowserCachePC=-1
BrowserCacheLG=1
DNSCachePC=1
DNSCacheLG=1
SSLCachePC=1
SSLCacheLG=1
HTTPVersion=1
KeepAlivePC=1
KeepAliveLG=1
RedirectionEnabled=1
RedirectionLimit=10
Browser types list=Microsoft Internet Explorer;Mozilla Firefox;Chrome;Safari;Opera;iPhone;Android Webkit Browser;BlackBerry;Opera Mini;S60 Nokia Browser;Unix/Linux;WAP;Default;
Microsoft Internet Explorer=0|Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 7.1; Trident/5.0)|Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET CLR 1.0.3705; .NET CLR 1.1.4322)|Mozilla/5.0 (Windows; U; MSIE 7.0; Windows NT 6.0; en-US)|
Mozilla Firefox=0|Mozilla/5.0 (X11; Linux i686; rv:6.0) Gecko/20100101 Firefox/6.0|Mozilla/5.0 (Windows NT 6.1; WOW64; rv:5.0) Gecko/20100101 Firefox/5.0|Mozilla/5.0 (Windows NT 6.1; rv:1.9) Gecko/20100101 Firefox/4.0|
Chrome=0|Mozilla/5.0 (Windows NT 5.1) AppleWebKit/535.6 (KHTML, like Gecko) Chrome/16.0.897.0 Safari/535.6|
Safari=0|Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_8; de-at) AppleWebKit/533.21.1 (KHTML, like Gecko) Version/5.0.5 Safari/533.21.1|
Opera=0|Opera/9.80 (Windows NT 6.1; U; es-ES) Presto/2.9.181 Version/12.00|
iPhone=0|Mozilla/5.0 (iPhone; CPU iPhone OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A334 Safari/7534.48.3|
Android Webkit Browser=0|Mozilla/5.0 (Linux; U; Android 2.3.5; en-us; HTC Vision Build/GRI40) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1|
BlackBerry=0|Mozilla/5.0 (BlackBerry; U; BlackBerry 9850; en-US) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.0.0.115 Mobile Safari/534.11+|
Opera Mini=0|Opera/9.80 (J2ME/MIDP; Opera Mini/9.80 (S60; SymbOS; Opera Mobi/23.348; U; en) Presto/2.5.25 Version/10.54|
S60 Nokia Browser=0|NokiaN97i/SymbianOS/9.1 Series60/3.0|
Unix/Linux=0|Lynx/2.6 libwww-FM/2.14|Mozilla/4.04[en](X11;I;Linux 2.0.33 i586)|
WAP=0|Alcatel OneTouch|Generic digital phone|Mitsubishi MobileAccess|Samsung Duette|Motorola i1000plus|
Default=0|Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0)|
Selected Browser Type=Default
Selected User Agent=Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)
SSL Cypher Suite=None
SSL Cypher Suite Enabled=0
Encoding Value=0
EnforceEncoding=0
bGZipSupport=0
[NectarToolbar_EXE_download : Authentication]
UserName=
PassWord=
NTUserName=
NTUserPassword=
KerberosServer=
AuthType=0
ProxyUserName=
ProxyPassWord=
SSLClientCertificateFile=
SSLClientCertificatePassword=
ProxyHost=
ProxyPort=
[NectarToolbar_EXE_download : Options\Connection]
Speed for LG=
Speed for PC=
Is Compression Rate for LG=0
Is Compression Rate for PC=0
Is Speed for LG=0
Is Speed for PC=0
Compression Rate for LG( in )=0
Compression Rate for LG( out )=0
Compression Rate for PC( out )=0
Compression Rate for PC( in )=0
[NectarToolbar_EXE_download : Diagnostic]
Start Round=1
End Round=1
Output Dir=
Syntax Check=0
Log Check=0
Trace Check=0
Automatic State=0
SaveCSJS Check=0
CSJSDiagnosticMessages Check=0
[NectarToolbar_EXE_download : FunctionalTesting]
Transaction Failed=0
Failed Time=20
Verification Portion=2
Severity=2
Automatic Transaction=0
Verification=0
Object Level=0
HTTP Level=0
sTextSearch=
nCompareTitle=0
nFramesNumber=0
nTextSearch=0
nCompareLinks=0
nCompareForms=0
nCompareImages=0
nCompareTables=0
[NectarToolbar_EXE_download : ClientType]
clientType=5
getImages=1
UseClientJSFull=1
UseClientJSOptim=0
JavaFull=0
JavaOptimized=0
[NectarToolbar_EXE_download : PassFailDefinition]
definitionType=1
checkErrors=0
checkSevere=1
checkStopTest=0
checkWarnings=0
errorNum=5
ruleCheck=15
warningNum=15
[NectarToolbar_EXE_download : SleepTimeControl]
sleepControlType=1
timeBetween=2
timeAnd=10
deviationPersent=10
[NectarToolbar_EXE_download : BrowserDialogs]
BrowserDialogsOptions=<IE_OPTIONS Option_version=\"19\">\r\n\t<IE_DIALOG name=\"Alert\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Confirm\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Prompt\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Input\"></field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Print\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Cookie_IE6\">\r\n\t\t<Answer>\r\n\t\t\t<value>Allow</value>\r\n\t\t\t<value>Block</value>\r\n\t\t\t<default>Allow</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"ApplyToAll\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Cookie\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FormSubmit\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FormResubmit\">\r\n\t\t<Answer>\r\n\t\t\t<value>Retry</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Retry</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SwitchNonSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SwitchSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"NonSecureOnSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientAuthentication\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"string\" name=\"Domain\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ConnectToMS_WinXP\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Email\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"checkbox\" name=\"AutoSignIn\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientAuthentication_WinXP\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientCertificate\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Certificate\">\r\n\t\t\t<default>0</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"HostCertificate\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload_IE6\">\r\n\t\t<Answer>\r\n\t\t\t<value>Open</value>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload_IE6_XP\">\r\n\t\t<Answer>\r\n\t\t\t<value>Open</value>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SaveFile\">\r\n\t\t<Answer>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"FileName\"></field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SaveFileConfirmation\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ActiveXInstall\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysTrust\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"RunActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"UnsafeActiveX\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ScriptAccessingActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"NavigateSubFrames\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ActiveScripting\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"JavaScripting\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Redirection\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"AutoComplete\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"RememberPassword\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"DoNotOffer\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FtpAuthentication\">\r\n\t\t<Answer>\r\n\t\t\t<value>Login</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Login</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Server\"></field>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"string\" name=\"Email\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Anonymous\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FtpFolderError\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"DocumentModified\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"JavascriptError\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"WindowClosing\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SuspiciousActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Reboot\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"YesNoCancel\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"YesNo\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"OkCancel\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Ok\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n</IE_OPTIONS>
[NectarToolbar_EXE_download : EmulationPlayback]
useHistory=0
historyLimit=1
csjsRecovery=1
[NectarToolbar_EXE_download : Java]
strSelectedJVM=Default
[NectarToolbar_EXE_download : WebServices]
sBasicPassword=
sUserName=
sProxyHost=
sProxyPassword=
sProxyUser=
sProxyPort=
nWSClientType=1
[NectarToolbar_EXE_download : ResetMechanism]
bResetEnable=0
nCreateLGRetryTimes=3
nLGTimeout=150
nResetTimeout=60
nStopLGTimeout=3
[NectarToolbar_EXE_download : HTTPParameters]
bHTTPVersion=1
bMultiIPSupport=0
bEncodeFormData=1
bAcceptLanguage=0
StrAcceptLanguage=
[NectarToolbar_EXE_download : BrowserCache]
bFilterApplets=1
bFilterImages=1
bFilterJSFiles=1
bFilterStyleSheets=1
bFilterXMLFiles=1
bFilterDynamic=0
nCacheType=3
bFilterAppletsPC=1
bFilterImagesPC=1
bFilterJSFilesPC=1
bFilterStyleSheetsPC=1
bFilterXMLFilesPC=1
bFilterDynamicPC=0
nCacheTypePC=3
[NectarToolbar_EXE_download@10.1.2.6]
StationType=PC
OperatingSystem=NT
ClientType=2
Type=Emulation
AssistentItemAAString_1=8 '11 RunLoadTime '3 180 '13 StartLoadSize '2 10 '12 RumpDownTime '1 1 '16 AssistantCaption '22 Ramp Up Schedule Model '13 ScheduleModel '1 6 '11 RunLoadSize '2 50 '10 RumpUpTime '2 10 '9 TotalTime '3 191 
Schedule_1=1
From_1=00000000
To_1=00000030
LoadSize_1=10
Schedule_2=1
From_2=00000030
To_2=00000100
LoadSize_2=12
Schedule_3=1
From_3=00000100
To_3=00000130
LoadSize_3=14
Schedule_4=1
From_4=00000130
To_4=00000200
LoadSize_4=16
Schedule_5=1
From_5=00000200
To_5=00000230
LoadSize_5=18
Schedule_6=1
From_6=00000230
To_6=00000300
LoadSize_6=20
Schedule_7=1
From_7=00000300
To_7=00000330
LoadSize_7=22
Schedule_8=1
From_8=00000330
To_8=00000400
LoadSize_8=24
Schedule_9=1
From_9=00000400
To_9=00000430
LoadSize_9=26
Schedule_10=1
From_10=00000430
To_10=00000500
LoadSize_10=28
Schedule_11=1
From_11=00000500
To_11=00000530
LoadSize_11=30
Schedule_12=1
From_12=00000530
To_12=00000600
LoadSize_12=32
Schedule_13=1
From_13=00000600
To_13=00000630
LoadSize_13=34
Schedule_14=1
From_14=00000630
To_14=00000700
LoadSize_14=36
Schedule_15=1
From_15=00000700
To_15=00000730
LoadSize_15=38
Schedule_16=1
From_16=00000730
To_16=00000800
LoadSize_16=40
Schedule_17=1
From_17=00000800
To_17=00000830
LoadSize_17=42
Schedule_18=1
From_18=00000830
To_18=00000900
LoadSize_18=44
Schedule_19=1
From_19=00000900
To_19=00000930
LoadSize_19=46
Schedule_20=1
From_20=00000930
To_20=00001000
LoadSize_20=48
Schedule_21=1
From_21=00001000
To_21=00031000
LoadSize_21=50
Schedule_22=1
From_22=00031000
To_22=00031030
LoadSize_22=30
Schedule_23=1
From_23=00031030
To_23=00031100
LoadSize_23=10
[NectarToolbar_EXE_download@10.1.2.5]
StationType=PC
OperatingSystem=NT
ClientType=2
Type=Emulation
AssistentItemAAString_1=8 '11 RunLoadTime '3 180 '13 StartLoadSize '2 10 '12 RumpDownTime '1 1 '16 AssistantCaption '22 Ramp Up Schedule Model '13 ScheduleModel '1 6 '11 RunLoadSize '2 50 '10 RumpUpTime '2 10 '9 TotalTime '3 191 
Schedule_1=1
From_1=00000000
To_1=00000030
LoadSize_1=10
Schedule_2=1
From_2=00000030
To_2=00000100
LoadSize_2=12
Schedule_3=1
From_3=00000100
To_3=00000130
LoadSize_3=14
Schedule_4=1
From_4=00000130
To_4=00000200
LoadSize_4=16
Schedule_5=1
From_5=00000200
To_5=00000230
LoadSize_5=18
Schedule_6=1
From_6=00000230
To_6=00000300
LoadSize_6=20
Schedule_7=1
From_7=00000300
To_7=00000330
LoadSize_7=22
Schedule_8=1
From_8=00000330
To_8=00000400
LoadSize_8=24
Schedule_9=1
From_9=00000400
To_9=00000430
LoadSize_9=26
Schedule_10=1
From_10=00000430
To_10=00000500
LoadSize_10=28
Schedule_11=1
From_11=00000500
To_11=00000530
LoadSize_11=30
Schedule_12=1
From_12=00000530
To_12=00000600
LoadSize_12=32
Schedule_13=1
From_13=00000600
To_13=00000630
LoadSize_13=34
Schedule_14=1
From_14=00000630
To_14=00000700
LoadSize_14=36
Schedule_15=1
From_15=00000700
To_15=00000730
LoadSize_15=38
Schedule_16=1
From_16=00000730
To_16=00000800
LoadSize_16=40
Schedule_17=1
From_17=00000800
To_17=00000830
LoadSize_17=42
Schedule_18=1
From_18=00000830
To_18=00000900
LoadSize_18=44
Schedule_19=1
From_19=00000900
To_19=00000930
LoadSize_19=46
Schedule_20=1
From_20=00000930
To_20=00001000
LoadSize_20=48
Schedule_21=1
From_21=00001000
To_21=00031000
LoadSize_21=50
Schedule_22=1
From_22=00031000
To_22=00031030
LoadSize_22=30
Schedule_23=1
From_23=00031030
To_23=00031100
LoadSize_23=10
[SMVDTree]
Hosts=
[Integrated Reports]
Reports=Default Report;;
[Default Report Tree]
Generators=Total;;
[TotalDefault Report]
Type=Web
Measurements=Load Size;;Hits Per Second;;Round Time;;Throughput (Bytes Per Second);;
[Load SizeTotalDefault Report]
Measurement Types=9;;
[9Load SizeTotalDefault Report]
maxValue=100.000000
AutoAdjustedValue=-1.000000
GroupAutoAdjustedValue=-2.000000
AutoAdjust=1
[Hits Per SecondTotalDefault Report]
Measurement Types=9;;
[9Hits Per SecondTotalDefault Report]
maxValue=100.000000
AutoAdjustedValue=-1.000000
GroupAutoAdjustedValue=-2.000000
AutoAdjust=1
[Round TimeTotalDefault Report]
Measurement Types=10;;
[10Round TimeTotalDefault Report]
maxValue=100.000000
AutoAdjustedValue=-1.000000
GroupAutoAdjustedValue=-2.000000
AutoAdjust=1
[Throughput (Bytes Per Second)TotalDefault Report]
Measurement Types=9;;
[9Throughput (Bytes Per Second)TotalDefault Report]
maxValue=100.000000
AutoAdjustedValue=-1.000000
GroupAutoAdjustedValue=-2.000000
AutoAdjust=1
[AdditionalInformation]
TemplateComments=
SessionComments=
CreatedBy=
Custom1=
Custom2=
Custom3=
Subject=
TestDescription=
ResultsDescription=
Title=Toolbar_Polling_Services
VersionBuild=
[NotificationManagerInfo]
TestDoneActionFromMail=
TestDoneActionToMail=
TestDoneActionSubject=
TestDoneActionMessageBody=
SendTestDoneMail=0
NotificationRulesNumber=0
