[main]
Version=5.000
StatManager Version=5.000
Report Version=5.000
Schedule Assistent Version=6.000
TemplateCreatedVersion=Version 9.0.0.118.00  Supports 128 bit SSL
TemplateLastSavedVersion=Version 10.0.0.124.00  Supports 128 bit SSL 
Agendas=OAPI_issue_Load_Test_Mix_RTR;
[OAPI_issue_Load_Test_Mix_RTR]
Path=C:\PerformanceTesting\Projects\STD_MIX\RTR\OAPI_issue_Load_Test_Mix_RTR.mix
ExecutionType=0
IsMix=1
AssistentItemAAString_1=8 '11 RunLoadTime '2 60 '13 StartLoadSize '1 4 '12 RumpDownTime '1 1 '16 AssistantCaption '22 Ramp Up Schedule Model '13 ScheduleModel '1 6 '11 RunLoadSize '3 120 '10 RumpUpTime '2 10 '9 TotalTime '2 71
Schedule_1=1
From_1=00000000
To_1=00000030
LoadSize_1=4
Schedule_2=1
From_2=00000030
To_2=00000100
LoadSize_2=9
Schedule_3=1
From_3=00000100
To_3=00000130
LoadSize_3=15
Schedule_4=1
From_4=00000130
To_4=00000200
LoadSize_4=21
Schedule_5=1
From_5=00000200
To_5=00000230
LoadSize_5=27
Schedule_6=1
From_6=00000230
To_6=00000300
LoadSize_6=33
Schedule_7=1
From_7=00000300
To_7=00000330
LoadSize_7=38
Schedule_8=1
From_8=00000330
To_8=00000400
LoadSize_8=44
Schedule_9=1
From_9=00000400
To_9=00000430
LoadSize_9=50
Schedule_10=1
From_10=00000430
To_10=00000500
LoadSize_10=56
Schedule_11=1
From_11=00000500
To_11=00000530
LoadSize_11=62
Schedule_12=1
From_12=00000530
To_12=00000600
LoadSize_12=67
Schedule_13=1
From_13=00000600
To_13=00000630
LoadSize_13=73
Schedule_14=1
From_14=00000630
To_14=00000700
LoadSize_14=79
Schedule_15=1
From_15=00000700
To_15=00000730
LoadSize_15=85
Schedule_16=1
From_16=00000730
To_16=00000800
LoadSize_16=91
Schedule_17=1
From_17=00000800
To_17=00000830
LoadSize_17=96
Schedule_18=1
From_18=00000830
To_18=00000900
LoadSize_18=102
Schedule_19=1
From_19=00000900
To_19=00000930
LoadSize_19=108
Schedule_20=1
From_20=00000930
To_20=00001000
LoadSize_20=114
Schedule_21=1
From_21=00001000
To_21=00011000
LoadSize_21=120
Schedule_22=1
From_22=00011000
To_22=00011030
LoadSize_22=62
Schedule_23=1
From_23=00011030
To_23=00011100
LoadSize_23=4
LoadMachines=192.168.33.12;192.168.33.14;192.168.33.15;192.168.33.16;
[Mix::Redeem_and_Reverse_Reward : Browser Emulation]
IsMultiThreadVirtualClientPC=0
IsMultiThreadVirtualClientLG=0
MultiThreadVirtualClientPCNum=1
MultiThreadVirtualClientLGNum=4
BrowserCachePC=0
BrowserCacheLG=1
DNSCachePC=1
DNSCacheLG=1
SSLCachePC=1
SSLCacheLG=1
HTTPVersion=1
KeepAlivePC=0
KeepAliveLG=1
RedirectionEnabled=1
RedirectionLimit=10
Selected Browser Type=Default
Selected User Agent=Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0)
SSL Cypher Suite=None
SSL Cypher Suite Enabled=0
Encoding Value=0
EnforceEncoding=0
bGZipSupport=0
[Mix::Redeem_and_Reverse_Reward : Authentication]
UserName=
PassWord=
NTUserName=
NTUserPassword=
KerberosServer=
AuthType=0
ProxyUserName=
ProxyPassWord=
SSLClientCertificateFile=
SSLClientCertificatePassword=
ProxyHost=
ProxyPort=
[Mix::Redeem_and_Reverse_Reward : Options\Connection]
Speed for LG=
Speed for PC=
Is Compression Rate for LG=0
Is Compression Rate for PC=0
Compression Rate for LG( in )=0
Compression Rate for LG( out )=0
Compression Rate for PC( out )=0
Compression Rate for PC( in )=0
[Mix::Redeem_and_Reverse_Reward : Diagnostic]
Start Round=1
End Round=1
Output Dir=
Syntax Check=0
Log Check=0
Trace Check=0
Automatic State=0
SaveCSJS Check=0
CSJSDiagnosticMessages Check=0
[Mix::Redeem_and_Reverse_Reward : FunctionalTesting]
Transaction Failed=0
Failed Time=20
Verification Portion=2
Severity=2
Automatic Transaction=0
Verification=0
Object Level=0
HTTP Level=0
sTextSearch=
nCompareTitle=0
nFramesNumber=0
nTextSearch=0
nCompareLinks=0
nCompareForms=0
nCompareImages=0
nCompareTables=0
[Mix::Redeem_and_Reverse_Reward : ClientType]
clientType=5
getImages=1
UseClientJSFull=1
UseClientJSOptim=0
JavaFull=0
JavaOptimized=0
[Mix::Redeem_and_Reverse_Reward : PassFailDefinition]
definitionType=1
checkErrors=0
checkSevere=1
checkStopTest=0
checkWarnings=0
errorNum=5
ruleCheck=15
warningNum=15
[Mix::Redeem_and_Reverse_Reward : SleepTimeControl]
sleepControlType=1
timeBetween=2
timeAnd=10
deviationPersent=10
[Mix::Redeem_and_Reverse_Reward : BrowserDialogs]
BrowserDialogsOptions=<IE_OPTIONS Option_version=\"19\">\r\n\t<IE_DIALOG name=\"Alert\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Confirm\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Prompt\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Input\"></field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Print\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Cookie_IE6\">\r\n\t\t<Answer>\r\n\t\t\t<value>Allow</value>\r\n\t\t\t<value>Block</value>\r\n\t\t\t<default>Allow</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"ApplyToAll\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Cookie\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FormSubmit\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FormResubmit\">\r\n\t\t<Answer>\r\n\t\t\t<value>Retry</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Retry</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SwitchNonSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SwitchSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"NonSecureOnSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientAuthentication\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"string\" name=\"Domain\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ConnectToMS_WinXP\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Email\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"checkbox\" name=\"AutoSignIn\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientAuthentication_WinXP\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientCertificate\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Certificate\">\r\n\t\t\t<default>0</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"HostCertificate\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload_IE6\">\r\n\t\t<Answer>\r\n\t\t\t<value>Open</value>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload_IE6_XP\">\r\n\t\t<Answer>\r\n\t\t\t<value>Open</value>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SaveFile\">\r\n\t\t<Answer>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"FileName\"></field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SaveFileConfirmation\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ActiveXInstall\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysTrust\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"RunActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"UnsafeActiveX\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ScriptAccessingActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"NavigateSubFrames\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ActiveScripting\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"JavaScripting\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Redirection\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"AutoComplete\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"RememberPassword\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"DoNotOffer\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FtpAuthentication\">\r\n\t\t<Answer>\r\n\t\t\t<value>Login</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Login</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Server\"></field>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"string\" name=\"Email\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Anonymous\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FtpFolderError\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"DocumentModified\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"JavascriptError\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"WindowClosing\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SuspiciousActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Reboot\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"YesNoCancel\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"YesNo\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"OkCancel\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Ok\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n</IE_OPTIONS>
[Mix::Redeem_and_Reverse_Reward : EmulationPlayback]
useHistory=0
historyLimit=1
csjsRecovery=1
[Mix::Redeem_and_Reverse_Reward : Java]
strSelectedJVM=Default
[Mix::Redeem_and_Reverse_Reward : WebServices]
sBasicPassword=
sUserName=
sProxyHost=
sProxyPassword=
sProxyUser=
sProxyPort=
nWSClientType=1
[Mix::Redeem_and_Reverse_Reward : ResetMechanism]
bResetEnable=0
nCreateLGRetryTimes=3
nLGTimeout=150
nResetTimeout=60
nStopLGTimeout=3
[Mix::Redeem_and_Reverse_Reward : HTTPParameters]
bHTTPVersion=1
bMultiIPSupport=0
bEncodeFormData=1
bAcceptLanguage=0
StrAcceptLanguage=
[Mix::Redeem_and_Reverse_Reward : BrowserCache]
bFilterApplets=1
bFilterImages=1
bFilterJSFiles=1
bFilterStyleSheets=1
bFilterXMLFiles=1
bFilterDynamic=0
nCacheType=3
bFilterAppletsPC=1
bFilterImagesPC=1
bFilterJSFilesPC=1
bFilterStyleSheetsPC=1
bFilterXMLFilesPC=1
bFilterDynamicPC=0
nCacheTypePC=3
[Mix::get_Collector_Basics : Browser Emulation]
IsMultiThreadVirtualClientPC=0
IsMultiThreadVirtualClientLG=0
MultiThreadVirtualClientPCNum=1
MultiThreadVirtualClientLGNum=4
BrowserCachePC=0
BrowserCacheLG=1
DNSCachePC=1
DNSCacheLG=1
SSLCachePC=1
SSLCacheLG=1
HTTPVersion=1
KeepAlivePC=0
KeepAliveLG=1
RedirectionEnabled=1
RedirectionLimit=10
Selected Browser Type=Default
Selected User Agent=Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0)
SSL Cypher Suite=None
SSL Cypher Suite Enabled=0
Encoding Value=0
EnforceEncoding=0
bGZipSupport=0
[Mix::get_Collector_Basics : Authentication]
UserName=
PassWord=
NTUserName=
NTUserPassword=
KerberosServer=
AuthType=0
ProxyUserName=
ProxyPassWord=
SSLClientCertificateFile=
SSLClientCertificatePassword=
ProxyHost=
ProxyPort=
[Mix::get_Collector_Basics : Options\Connection]
Speed for LG=
Speed for PC=
Is Compression Rate for LG=0
Is Compression Rate for PC=0
Compression Rate for LG( in )=0
Compression Rate for LG( out )=0
Compression Rate for PC( out )=0
Compression Rate for PC( in )=0
[Mix::get_Collector_Basics : Diagnostic]
Start Round=1
End Round=1
Output Dir=
Syntax Check=0
Log Check=0
Trace Check=0
Automatic State=0
SaveCSJS Check=0
CSJSDiagnosticMessages Check=0
[Mix::get_Collector_Basics : FunctionalTesting]
Transaction Failed=0
Failed Time=20
Verification Portion=2
Severity=2
Automatic Transaction=0
Verification=0
Object Level=0
HTTP Level=0
sTextSearch=
nCompareTitle=0
nFramesNumber=0
nTextSearch=0
nCompareLinks=0
nCompareForms=0
nCompareImages=0
nCompareTables=0
[Mix::get_Collector_Basics : ClientType]
clientType=5
getImages=1
UseClientJSFull=1
UseClientJSOptim=0
JavaFull=0
JavaOptimized=0
[Mix::get_Collector_Basics : PassFailDefinition]
definitionType=1
checkErrors=0
checkSevere=1
checkStopTest=0
checkWarnings=0
errorNum=5
ruleCheck=15
warningNum=15
[Mix::get_Collector_Basics : SleepTimeControl]
sleepControlType=1
timeBetween=2
timeAnd=10
deviationPersent=10
[Mix::get_Collector_Basics : BrowserDialogs]
BrowserDialogsOptions=<IE_OPTIONS Option_version=\"19\">\r\n\t<IE_DIALOG name=\"Alert\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Confirm\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Prompt\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Input\"></field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Print\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Cookie_IE6\">\r\n\t\t<Answer>\r\n\t\t\t<value>Allow</value>\r\n\t\t\t<value>Block</value>\r\n\t\t\t<default>Allow</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"ApplyToAll\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Cookie\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FormSubmit\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FormResubmit\">\r\n\t\t<Answer>\r\n\t\t\t<value>Retry</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Retry</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SwitchNonSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SwitchSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"NonSecureOnSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientAuthentication\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"string\" name=\"Domain\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ConnectToMS_WinXP\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Email\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"checkbox\" name=\"AutoSignIn\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientAuthentication_WinXP\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientCertificate\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Certificate\">\r\n\t\t\t<default>0</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"HostCertificate\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload_IE6\">\r\n\t\t<Answer>\r\n\t\t\t<value>Open</value>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload_IE6_XP\">\r\n\t\t<Answer>\r\n\t\t\t<value>Open</value>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SaveFile\">\r\n\t\t<Answer>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"FileName\"></field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SaveFileConfirmation\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ActiveXInstall\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysTrust\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"RunActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"UnsafeActiveX\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ScriptAccessingActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"NavigateSubFrames\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ActiveScripting\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"JavaScripting\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Redirection\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"AutoComplete\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"RememberPassword\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"DoNotOffer\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FtpAuthentication\">\r\n\t\t<Answer>\r\n\t\t\t<value>Login</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Login</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Server\"></field>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"string\" name=\"Email\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Anonymous\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FtpFolderError\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"DocumentModified\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"JavascriptError\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"WindowClosing\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SuspiciousActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Reboot\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"YesNoCancel\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"YesNo\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"OkCancel\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Ok\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n</IE_OPTIONS>
[Mix::get_Collector_Basics : EmulationPlayback]
useHistory=0
historyLimit=1
csjsRecovery=1
[Mix::get_Collector_Basics : Java]
strSelectedJVM=Default
[Mix::get_Collector_Basics : WebServices]
sBasicPassword=
sUserName=
sProxyHost=
sProxyPassword=
sProxyUser=
sProxyPort=
nWSClientType=1
[Mix::get_Collector_Basics : ResetMechanism]
bResetEnable=0
nCreateLGRetryTimes=3
nLGTimeout=150
nResetTimeout=60
nStopLGTimeout=3
[Mix::get_Collector_Basics : HTTPParameters]
bHTTPVersion=1
bMultiIPSupport=0
bEncodeFormData=1
bAcceptLanguage=0
StrAcceptLanguage=
[Mix::get_Collector_Basics : BrowserCache]
bFilterApplets=1
bFilterImages=1
bFilterJSFiles=1
bFilterStyleSheets=1
bFilterXMLFiles=1
bFilterDynamic=0
nCacheType=3
bFilterAppletsPC=1
bFilterImagesPC=1
bFilterJSFilesPC=1
bFilterStyleSheetsPC=1
bFilterXMLFilesPC=1
bFilterDynamicPC=0
nCacheTypePC=3
[Mix::get_Collector_Details : Browser Emulation]
IsMultiThreadVirtualClientPC=0
IsMultiThreadVirtualClientLG=0
MultiThreadVirtualClientPCNum=1
MultiThreadVirtualClientLGNum=4
BrowserCachePC=0
BrowserCacheLG=1
DNSCachePC=1
DNSCacheLG=1
SSLCachePC=1
SSLCacheLG=1
HTTPVersion=1
KeepAlivePC=0
KeepAliveLG=1
RedirectionEnabled=1
RedirectionLimit=10
Selected Browser Type=Default
Selected User Agent=Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0)
SSL Cypher Suite=None
SSL Cypher Suite Enabled=0
Encoding Value=0
EnforceEncoding=0
bGZipSupport=0
[Mix::get_Collector_Details : Authentication]
UserName=
PassWord=
NTUserName=
NTUserPassword=
KerberosServer=
AuthType=0
ProxyUserName=
ProxyPassWord=
SSLClientCertificateFile=
SSLClientCertificatePassword=
ProxyHost=
ProxyPort=
[Mix::get_Collector_Details : Options\Connection]
Speed for LG=
Speed for PC=
Is Compression Rate for LG=0
Is Compression Rate for PC=0
Compression Rate for LG( in )=0
Compression Rate for LG( out )=0
Compression Rate for PC( out )=0
Compression Rate for PC( in )=0
[Mix::get_Collector_Details : Diagnostic]
Start Round=1
End Round=1
Output Dir=
Syntax Check=0
Log Check=0
Trace Check=0
Automatic State=0
SaveCSJS Check=0
CSJSDiagnosticMessages Check=0
[Mix::get_Collector_Details : FunctionalTesting]
Transaction Failed=0
Failed Time=20
Verification Portion=2
Severity=2
Automatic Transaction=0
Verification=0
Object Level=0
HTTP Level=0
sTextSearch=
nCompareTitle=0
nFramesNumber=0
nTextSearch=0
nCompareLinks=0
nCompareForms=0
nCompareImages=0
nCompareTables=0
[Mix::get_Collector_Details : ClientType]
clientType=5
getImages=1
UseClientJSFull=1
UseClientJSOptim=0
JavaFull=0
JavaOptimized=0
[Mix::get_Collector_Details : PassFailDefinition]
definitionType=1
checkErrors=0
checkSevere=1
checkStopTest=0
checkWarnings=0
errorNum=5
ruleCheck=15
warningNum=15
[Mix::get_Collector_Details : SleepTimeControl]
sleepControlType=1
timeBetween=2
timeAnd=10
deviationPersent=10
[Mix::get_Collector_Details : BrowserDialogs]
BrowserDialogsOptions=<IE_OPTIONS Option_version=\"19\">\r\n\t<IE_DIALOG name=\"Alert\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Confirm\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Prompt\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Input\"></field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Print\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Cookie_IE6\">\r\n\t\t<Answer>\r\n\t\t\t<value>Allow</value>\r\n\t\t\t<value>Block</value>\r\n\t\t\t<default>Allow</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"ApplyToAll\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Cookie\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FormSubmit\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FormResubmit\">\r\n\t\t<Answer>\r\n\t\t\t<value>Retry</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Retry</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SwitchNonSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SwitchSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"NonSecureOnSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientAuthentication\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"string\" name=\"Domain\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ConnectToMS_WinXP\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Email\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"checkbox\" name=\"AutoSignIn\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientAuthentication_WinXP\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientCertificate\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Certificate\">\r\n\t\t\t<default>0</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"HostCertificate\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload_IE6\">\r\n\t\t<Answer>\r\n\t\t\t<value>Open</value>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload_IE6_XP\">\r\n\t\t<Answer>\r\n\t\t\t<value>Open</value>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SaveFile\">\r\n\t\t<Answer>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"FileName\"></field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SaveFileConfirmation\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ActiveXInstall\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysTrust\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"RunActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"UnsafeActiveX\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ScriptAccessingActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"NavigateSubFrames\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ActiveScripting\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"JavaScripting\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Redirection\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"AutoComplete\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"RememberPassword\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"DoNotOffer\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FtpAuthentication\">\r\n\t\t<Answer>\r\n\t\t\t<value>Login</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Login</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Server\"></field>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"string\" name=\"Email\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Anonymous\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FtpFolderError\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"DocumentModified\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"JavascriptError\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"WindowClosing\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SuspiciousActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Reboot\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"YesNoCancel\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"YesNo\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"OkCancel\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Ok\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n</IE_OPTIONS>
[Mix::get_Collector_Details : EmulationPlayback]
useHistory=0
historyLimit=1
csjsRecovery=1
[Mix::get_Collector_Details : Java]
strSelectedJVM=Default
[Mix::get_Collector_Details : WebServices]
sBasicPassword=
sUserName=
sProxyHost=
sProxyPassword=
sProxyUser=
sProxyPort=
nWSClientType=1
[Mix::get_Collector_Details : ResetMechanism]
bResetEnable=0
nCreateLGRetryTimes=3
nLGTimeout=150
nResetTimeout=60
nStopLGTimeout=3
[Mix::get_Collector_Details : HTTPParameters]
bHTTPVersion=1
bMultiIPSupport=0
bEncodeFormData=1
bAcceptLanguage=0
StrAcceptLanguage=
[Mix::get_Collector_Details : BrowserCache]
bFilterApplets=1
bFilterImages=1
bFilterJSFiles=1
bFilterStyleSheets=1
bFilterXMLFiles=1
bFilterDynamic=0
nCacheType=3
bFilterAppletsPC=1
bFilterImagesPC=1
bFilterJSFilesPC=1
bFilterStyleSheetsPC=1
bFilterXMLFilesPC=1
bFilterDynamicPC=0
nCacheTypePC=3
[Mix::Redeem_and_Reverse_Basket : Browser Emulation]
IsMultiThreadVirtualClientPC=0
IsMultiThreadVirtualClientLG=0
MultiThreadVirtualClientPCNum=1
MultiThreadVirtualClientLGNum=4
BrowserCachePC=0
BrowserCacheLG=1
DNSCachePC=1
DNSCacheLG=1
SSLCachePC=1
SSLCacheLG=1
HTTPVersion=1
KeepAlivePC=0
KeepAliveLG=1
RedirectionEnabled=1
RedirectionLimit=10
Selected Browser Type=Default
Selected User Agent=Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0)
SSL Cypher Suite=None
SSL Cypher Suite Enabled=0
Encoding Value=0
EnforceEncoding=0
bGZipSupport=0
[Mix::Redeem_and_Reverse_Basket : Authentication]
UserName=
PassWord=
NTUserName=
NTUserPassword=
KerberosServer=
AuthType=0
ProxyUserName=
ProxyPassWord=
SSLClientCertificateFile=
SSLClientCertificatePassword=
ProxyHost=
ProxyPort=
[Mix::Redeem_and_Reverse_Basket : Options\Connection]
Speed for LG=
Speed for PC=
Is Compression Rate for LG=0
Is Compression Rate for PC=0
Compression Rate for LG( in )=0
Compression Rate for LG( out )=0
Compression Rate for PC( out )=0
Compression Rate for PC( in )=0
[Mix::Redeem_and_Reverse_Basket : Diagnostic]
Start Round=1
End Round=1
Output Dir=
Syntax Check=0
Log Check=0
Trace Check=0
Automatic State=0
SaveCSJS Check=0
CSJSDiagnosticMessages Check=0
[Mix::Redeem_and_Reverse_Basket : FunctionalTesting]
Transaction Failed=0
Failed Time=20
Verification Portion=2
Severity=2
Automatic Transaction=0
Verification=0
Object Level=0
HTTP Level=0
sTextSearch=
nCompareTitle=0
nFramesNumber=0
nTextSearch=0
nCompareLinks=0
nCompareForms=0
nCompareImages=0
nCompareTables=0
[Mix::Redeem_and_Reverse_Basket : ClientType]
clientType=5
getImages=1
UseClientJSFull=1
UseClientJSOptim=0
JavaFull=0
JavaOptimized=0
[Mix::Redeem_and_Reverse_Basket : PassFailDefinition]
definitionType=1
checkErrors=0
checkSevere=1
checkStopTest=0
checkWarnings=0
errorNum=5
ruleCheck=15
warningNum=15
[Mix::Redeem_and_Reverse_Basket : SleepTimeControl]
sleepControlType=1
timeBetween=2
timeAnd=10
deviationPersent=10
[Mix::Redeem_and_Reverse_Basket : BrowserDialogs]
BrowserDialogsOptions=<IE_OPTIONS Option_version=\"19\">\r\n\t<IE_DIALOG name=\"Alert\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Confirm\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Prompt\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Input\"></field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Print\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Cookie_IE6\">\r\n\t\t<Answer>\r\n\t\t\t<value>Allow</value>\r\n\t\t\t<value>Block</value>\r\n\t\t\t<default>Allow</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"ApplyToAll\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Cookie\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FormSubmit\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FormResubmit\">\r\n\t\t<Answer>\r\n\t\t\t<value>Retry</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Retry</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SwitchNonSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SwitchSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"NonSecureOnSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientAuthentication\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"string\" name=\"Domain\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ConnectToMS_WinXP\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Email\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"checkbox\" name=\"AutoSignIn\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientAuthentication_WinXP\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientCertificate\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Certificate\">\r\n\t\t\t<default>0</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"HostCertificate\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload_IE6\">\r\n\t\t<Answer>\r\n\t\t\t<value>Open</value>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload_IE6_XP\">\r\n\t\t<Answer>\r\n\t\t\t<value>Open</value>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SaveFile\">\r\n\t\t<Answer>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"FileName\"></field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SaveFileConfirmation\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ActiveXInstall\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysTrust\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"RunActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"UnsafeActiveX\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ScriptAccessingActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"NavigateSubFrames\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ActiveScripting\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"JavaScripting\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Redirection\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"AutoComplete\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"RememberPassword\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"DoNotOffer\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FtpAuthentication\">\r\n\t\t<Answer>\r\n\t\t\t<value>Login</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Login</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Server\"></field>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"string\" name=\"Email\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Anonymous\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FtpFolderError\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"DocumentModified\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"JavascriptError\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"WindowClosing\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SuspiciousActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Reboot\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"YesNoCancel\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"YesNo\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"OkCancel\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Ok\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n</IE_OPTIONS>
[Mix::Redeem_and_Reverse_Basket : EmulationPlayback]
useHistory=0
historyLimit=1
csjsRecovery=1
[Mix::Redeem_and_Reverse_Basket : Java]
strSelectedJVM=Default
[Mix::Redeem_and_Reverse_Basket : WebServices]
sBasicPassword=
sUserName=
sProxyHost=
sProxyPassword=
sProxyUser=
sProxyPort=
nWSClientType=1
[Mix::Redeem_and_Reverse_Basket : ResetMechanism]
bResetEnable=0
nCreateLGRetryTimes=3
nLGTimeout=150
nResetTimeout=60
nStopLGTimeout=3
[Mix::Redeem_and_Reverse_Basket : HTTPParameters]
bHTTPVersion=1
bMultiIPSupport=0
bEncodeFormData=1
bAcceptLanguage=0
StrAcceptLanguage=
[Mix::Redeem_and_Reverse_Basket : BrowserCache]
bFilterApplets=1
bFilterImages=1
bFilterJSFiles=1
bFilterStyleSheets=1
bFilterXMLFiles=1
bFilterDynamic=0
nCacheType=3
bFilterAppletsPC=1
bFilterImagesPC=1
bFilterJSFilesPC=1
bFilterStyleSheetsPC=1
bFilterXMLFilesPC=1
bFilterDynamicPC=0
nCacheTypePC=3
[Mix::get_Collector_Address : Browser Emulation]
IsMultiThreadVirtualClientPC=0
IsMultiThreadVirtualClientLG=0
MultiThreadVirtualClientPCNum=1
MultiThreadVirtualClientLGNum=4
BrowserCachePC=0
BrowserCacheLG=1
DNSCachePC=1
DNSCacheLG=1
SSLCachePC=1
SSLCacheLG=1
HTTPVersion=1
KeepAlivePC=0
KeepAliveLG=1
RedirectionEnabled=1
RedirectionLimit=10
Selected Browser Type=Default
Selected User Agent=Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0)
SSL Cypher Suite=None
SSL Cypher Suite Enabled=0
Encoding Value=0
EnforceEncoding=0
bGZipSupport=0
[Mix::get_Collector_Address : Authentication]
UserName=
PassWord=
NTUserName=
NTUserPassword=
KerberosServer=
AuthType=0
ProxyUserName=
ProxyPassWord=
SSLClientCertificateFile=
SSLClientCertificatePassword=
ProxyHost=
ProxyPort=
[Mix::get_Collector_Address : Options\Connection]
Speed for LG=
Speed for PC=
Is Compression Rate for LG=0
Is Compression Rate for PC=0
Compression Rate for LG( in )=0
Compression Rate for LG( out )=0
Compression Rate for PC( out )=0
Compression Rate for PC( in )=0
[Mix::get_Collector_Address : Diagnostic]
Start Round=1
End Round=1
Output Dir=
Syntax Check=0
Log Check=0
Trace Check=0
Automatic State=0
SaveCSJS Check=0
CSJSDiagnosticMessages Check=0
[Mix::get_Collector_Address : FunctionalTesting]
Transaction Failed=0
Failed Time=20
Verification Portion=2
Severity=2
Automatic Transaction=0
Verification=0
Object Level=0
HTTP Level=0
sTextSearch=
nCompareTitle=0
nFramesNumber=0
nTextSearch=0
nCompareLinks=0
nCompareForms=0
nCompareImages=0
nCompareTables=0
[Mix::get_Collector_Address : ClientType]
clientType=5
getImages=1
UseClientJSFull=1
UseClientJSOptim=0
JavaFull=0
JavaOptimized=0
[Mix::get_Collector_Address : PassFailDefinition]
definitionType=1
checkErrors=0
checkSevere=1
checkStopTest=0
checkWarnings=0
errorNum=5
ruleCheck=15
warningNum=15
[Mix::get_Collector_Address : SleepTimeControl]
sleepControlType=1
timeBetween=2
timeAnd=10
deviationPersent=10
[Mix::get_Collector_Address : BrowserDialogs]
BrowserDialogsOptions=<IE_OPTIONS Option_version=\"19\">\r\n\t<IE_DIALOG name=\"Alert\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Confirm\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Prompt\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Input\"></field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Print\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Cookie_IE6\">\r\n\t\t<Answer>\r\n\t\t\t<value>Allow</value>\r\n\t\t\t<value>Block</value>\r\n\t\t\t<default>Allow</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"ApplyToAll\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Cookie\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FormSubmit\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FormResubmit\">\r\n\t\t<Answer>\r\n\t\t\t<value>Retry</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Retry</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SwitchNonSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SwitchSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"NonSecureOnSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientAuthentication\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"string\" name=\"Domain\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ConnectToMS_WinXP\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Email\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"checkbox\" name=\"AutoSignIn\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientAuthentication_WinXP\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientCertificate\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Certificate\">\r\n\t\t\t<default>0</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"HostCertificate\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload_IE6\">\r\n\t\t<Answer>\r\n\t\t\t<value>Open</value>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload_IE6_XP\">\r\n\t\t<Answer>\r\n\t\t\t<value>Open</value>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SaveFile\">\r\n\t\t<Answer>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"FileName\"></field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SaveFileConfirmation\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ActiveXInstall\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysTrust\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"RunActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"UnsafeActiveX\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ScriptAccessingActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"NavigateSubFrames\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ActiveScripting\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"JavaScripting\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Redirection\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"AutoComplete\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"RememberPassword\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"DoNotOffer\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FtpAuthentication\">\r\n\t\t<Answer>\r\n\t\t\t<value>Login</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Login</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Server\"></field>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"string\" name=\"Email\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Anonymous\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FtpFolderError\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"DocumentModified\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"JavascriptError\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"WindowClosing\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SuspiciousActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Reboot\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"YesNoCancel\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"YesNo\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"OkCancel\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Ok\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n</IE_OPTIONS>
[Mix::get_Collector_Address : EmulationPlayback]
useHistory=0
historyLimit=1
csjsRecovery=1
[Mix::get_Collector_Address : Java]
strSelectedJVM=Default
[Mix::get_Collector_Address : WebServices]
sBasicPassword=
sUserName=
sProxyHost=
sProxyPassword=
sProxyUser=
sProxyPort=
nWSClientType=1
[Mix::get_Collector_Address : ResetMechanism]
bResetEnable=0
nCreateLGRetryTimes=3
nLGTimeout=150
nResetTimeout=60
nStopLGTimeout=3
[Mix::get_Collector_Address : HTTPParameters]
bHTTPVersion=1
bMultiIPSupport=0
bEncodeFormData=1
bAcceptLanguage=0
StrAcceptLanguage=
[Mix::get_Collector_Address : BrowserCache]
bFilterApplets=1
bFilterImages=1
bFilterJSFiles=1
bFilterStyleSheets=1
bFilterXMLFiles=1
bFilterDynamic=0
nCacheType=3
bFilterAppletsPC=1
bFilterImagesPC=1
bFilterJSFilesPC=1
bFilterStyleSheetsPC=1
bFilterXMLFilesPC=1
bFilterDynamicPC=0
nCacheTypePC=3
[Mix::get_Point_Balance : Browser Emulation]
IsMultiThreadVirtualClientPC=0
IsMultiThreadVirtualClientLG=0
MultiThreadVirtualClientPCNum=1
MultiThreadVirtualClientLGNum=4
BrowserCachePC=0
BrowserCacheLG=1
DNSCachePC=1
DNSCacheLG=1
SSLCachePC=1
SSLCacheLG=1
HTTPVersion=1
KeepAlivePC=0
KeepAliveLG=1
RedirectionEnabled=1
RedirectionLimit=10
Selected Browser Type=Default
Selected User Agent=Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0)
SSL Cypher Suite=None
SSL Cypher Suite Enabled=0
Encoding Value=0
EnforceEncoding=0
bGZipSupport=0
[Mix::get_Point_Balance : Authentication]
UserName=
PassWord=
NTUserName=
NTUserPassword=
KerberosServer=
AuthType=0
ProxyUserName=
ProxyPassWord=
SSLClientCertificateFile=
SSLClientCertificatePassword=
ProxyHost=
ProxyPort=
[Mix::get_Point_Balance : Options\Connection]
Speed for LG=
Speed for PC=
Is Compression Rate for LG=0
Is Compression Rate for PC=0
Compression Rate for LG( in )=0
Compression Rate for LG( out )=0
Compression Rate for PC( out )=0
Compression Rate for PC( in )=0
[Mix::get_Point_Balance : Diagnostic]
Start Round=1
End Round=1
Output Dir=
Syntax Check=0
Log Check=0
Trace Check=0
Automatic State=0
SaveCSJS Check=0
CSJSDiagnosticMessages Check=0
[Mix::get_Point_Balance : FunctionalTesting]
Transaction Failed=0
Failed Time=20
Verification Portion=2
Severity=2
Automatic Transaction=0
Verification=0
Object Level=0
HTTP Level=0
sTextSearch=
nCompareTitle=0
nFramesNumber=0
nTextSearch=0
nCompareLinks=0
nCompareForms=0
nCompareImages=0
nCompareTables=0
[Mix::get_Point_Balance : ClientType]
clientType=5
getImages=1
UseClientJSFull=1
UseClientJSOptim=0
JavaFull=0
JavaOptimized=0
[Mix::get_Point_Balance : PassFailDefinition]
definitionType=1
checkErrors=0
checkSevere=1
checkStopTest=0
checkWarnings=0
errorNum=5
ruleCheck=15
warningNum=15
[Mix::get_Point_Balance : SleepTimeControl]
sleepControlType=1
timeBetween=2
timeAnd=10
deviationPersent=10
[Mix::get_Point_Balance : BrowserDialogs]
BrowserDialogsOptions=<IE_OPTIONS Option_version=\"19\">\r\n\t<IE_DIALOG name=\"Alert\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Confirm\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Prompt\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Input\"></field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Print\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Cookie_IE6\">\r\n\t\t<Answer>\r\n\t\t\t<value>Allow</value>\r\n\t\t\t<value>Block</value>\r\n\t\t\t<default>Allow</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"ApplyToAll\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Cookie\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FormSubmit\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FormResubmit\">\r\n\t\t<Answer>\r\n\t\t\t<value>Retry</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Retry</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SwitchNonSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SwitchSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"NonSecureOnSecure\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientAuthentication\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"string\" name=\"Domain\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ConnectToMS_WinXP\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Email\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"checkbox\" name=\"AutoSignIn\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientAuthentication_WinXP\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ClientCertificate\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Certificate\">\r\n\t\t\t<default>0</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"HostCertificate\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload_IE6\">\r\n\t\t<Answer>\r\n\t\t\t<value>Open</value>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FileDownload_IE6_XP\">\r\n\t\t<Answer>\r\n\t\t\t<value>Open</value>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysAsk\">\r\n\t\t\t<default>checked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SaveFile\">\r\n\t\t<Answer>\r\n\t\t\t<value>Save</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Save</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"FileName\"></field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SaveFileConfirmation\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ActiveXInstall\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"AlwaysTrust\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"RunActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"UnsafeActiveX\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ScriptAccessingActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"NavigateSubFrames\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"ActiveScripting\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"JavaScripting\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Redirection\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"NeverShow\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"AutoComplete\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"RememberPassword\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"checkbox\" name=\"DoNotOffer\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FtpAuthentication\">\r\n\t\t<Answer>\r\n\t\t\t<value>Login</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Login</default>\r\n\t\t</Answer>\r\n\t\t<field type=\"string\" name=\"Server\"></field>\r\n\t\t<field type=\"string\" name=\"Username\"></field>\r\n\t\t<field type=\"string\" name=\"Password\"></field>\r\n\t\t<field type=\"string\" name=\"Email\"></field>\r\n\t\t<field type=\"checkbox\" name=\"Anonymous\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t\t<field type=\"checkbox\" name=\"Save\">\r\n\t\t\t<default>unchecked</default>\r\n\t\t</field>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"FtpFolderError\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"DocumentModified\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"JavascriptError\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"WindowClosing\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"SuspiciousActiveX\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Reboot\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>No</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"YesNoCancel\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"YesNo\">\r\n\t\t<Answer>\r\n\t\t\t<value>Yes</value>\r\n\t\t\t<value>No</value>\r\n\t\t\t<default>Yes</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"OkCancel\">\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<value>Cancel</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n\t<IE_DIALOG name=\"Ok\">\r\n\t\t<readonly>yes</readonly>\r\n\t\t<Answer>\r\n\t\t\t<value>OK</value>\r\n\t\t\t<default>OK</default>\r\n\t\t</Answer>\r\n\t</IE_DIALOG>\r\n</IE_OPTIONS>
[Mix::get_Point_Balance : EmulationPlayback]
useHistory=0
historyLimit=1
csjsRecovery=1
[Mix::get_Point_Balance : Java]
strSelectedJVM=Default
[Mix::get_Point_Balance : WebServices]
sBasicPassword=
sUserName=
sProxyHost=
sProxyPassword=
sProxyUser=
sProxyPort=
nWSClientType=1
[Mix::get_Point_Balance : ResetMechanism]
bResetEnable=0
nCreateLGRetryTimes=3
nLGTimeout=150
nResetTimeout=60
nStopLGTimeout=3
[Mix::get_Point_Balance : HTTPParameters]
bHTTPVersion=1
bMultiIPSupport=0
bEncodeFormData=1
bAcceptLanguage=0
StrAcceptLanguage=
[Mix::get_Point_Balance : BrowserCache]
bFilterApplets=1
bFilterImages=1
bFilterJSFiles=1
bFilterStyleSheets=1
bFilterXMLFiles=1
bFilterDynamic=0
nCacheType=3
bFilterAppletsPC=1
bFilterImagesPC=1
bFilterJSFilesPC=1
bFilterStyleSheetsPC=1
bFilterXMLFilesPC=1
bFilterDynamicPC=0
nCacheTypePC=3
[OAPI_issue_Load_Test_Mix_RTR@192.168.33.12]
StationType=PC
OperatingSystem=NT
ClientType=2
Type=Emulation
AssistentItemAAString_1=8 '11 RunLoadTime '2 60 '13 StartLoadSize '1 1 '12 RumpDownTime '1 1 '16 AssistantCaption '22 Ramp Up Schedule Model '13 ScheduleModel '1 6 '11 RunLoadSize '2 30 '10 RumpUpTime '2 10 '9 TotalTime '2 71 
Schedule_1=1
From_1=00000000
To_1=00000030
LoadSize_1=1
Schedule_2=1
From_2=00000030
To_2=00000100
LoadSize_2=3
Schedule_3=1
From_3=00000100
To_3=00000130
LoadSize_3=4
Schedule_4=1
From_4=00000130
To_4=00000200
LoadSize_4=6
Schedule_5=1
From_5=00000200
To_5=00000230
LoadSize_5=7
Schedule_6=1
From_6=00000230
To_6=00000300
LoadSize_6=9
Schedule_7=1
From_7=00000300
To_7=00000330
LoadSize_7=10
Schedule_8=1
From_8=00000330
To_8=00000400
LoadSize_8=11
Schedule_9=1
From_9=00000400
To_9=00000430
LoadSize_9=13
Schedule_10=1
From_10=00000430
To_10=00000500
LoadSize_10=14
Schedule_11=1
From_11=00000500
To_11=00000530
LoadSize_11=16
Schedule_12=1
From_12=00000530
To_12=00000600
LoadSize_12=17
Schedule_13=1
From_13=00000600
To_13=00000630
LoadSize_13=19
Schedule_14=1
From_14=00000630
To_14=00000700
LoadSize_14=20
Schedule_15=1
From_15=00000700
To_15=00000730
LoadSize_15=22
Schedule_16=1
From_16=00000730
To_16=00000800
LoadSize_16=23
Schedule_17=1
From_17=00000800
To_17=00000830
LoadSize_17=24
Schedule_18=1
From_18=00000830
To_18=00000900
LoadSize_18=26
Schedule_19=1
From_19=00000900
To_19=00000930
LoadSize_19=27
Schedule_20=1
From_20=00000930
To_20=00001000
LoadSize_20=29
Schedule_21=1
From_21=00001000
To_21=00011000
LoadSize_21=30
Schedule_22=1
From_22=00011000
To_22=00011030
LoadSize_22=16
Schedule_23=1
From_23=00011030
To_23=00011100
LoadSize_23=1
[OAPI_issue_Load_Test_Mix_RTR@192.168.33.14]
StationType=PC
OperatingSystem=NT
ClientType=2
Type=Emulation
AssistentItemAAString_1=8 '11 RunLoadTime '2 60 '13 StartLoadSize '1 1 '12 RumpDownTime '1 1 '16 AssistantCaption '22 Ramp Up Schedule Model '13 ScheduleModel '1 6 '11 RunLoadSize '2 30 '10 RumpUpTime '2 10 '9 TotalTime '2 71 
Schedule_1=1
From_1=00000000
To_1=00000030
LoadSize_1=1
Schedule_2=1
From_2=00000030
To_2=00000100
LoadSize_2=2
Schedule_3=1
From_3=00000100
To_3=00000130
LoadSize_3=4
Schedule_4=1
From_4=00000130
To_4=00000200
LoadSize_4=5
Schedule_5=1
From_5=00000200
To_5=00000230
LoadSize_5=7
Schedule_6=1
From_6=00000230
To_6=00000300
LoadSize_6=8
Schedule_7=1
From_7=00000300
To_7=00000330
LoadSize_7=10
Schedule_8=1
From_8=00000330
To_8=00000400
LoadSize_8=11
Schedule_9=1
From_9=00000400
To_9=00000430
LoadSize_9=13
Schedule_10=1
From_10=00000430
To_10=00000500
LoadSize_10=14
Schedule_11=1
From_11=00000500
To_11=00000530
LoadSize_11=16
Schedule_12=1
From_12=00000530
To_12=00000600
LoadSize_12=17
Schedule_13=1
From_13=00000600
To_13=00000630
LoadSize_13=18
Schedule_14=1
From_14=00000630
To_14=00000700
LoadSize_14=20
Schedule_15=1
From_15=00000700
To_15=00000730
LoadSize_15=21
Schedule_16=1
From_16=00000730
To_16=00000800
LoadSize_16=23
Schedule_17=1
From_17=00000800
To_17=00000830
LoadSize_17=24
Schedule_18=1
From_18=00000830
To_18=00000900
LoadSize_18=26
Schedule_19=1
From_19=00000900
To_19=00000930
LoadSize_19=27
Schedule_20=1
From_20=00000930
To_20=00001000
LoadSize_20=29
Schedule_21=1
From_21=00001000
To_21=00011000
LoadSize_21=30
Schedule_22=1
From_22=00011000
To_22=00011030
LoadSize_22=16
Schedule_23=1
From_23=00011030
To_23=00011100
LoadSize_23=1
[OAPI_issue_Load_Test_Mix_RTR@192.168.33.15]
StationType=PC
OperatingSystem=NT
ClientType=2
Type=Emulation
AssistentItemAAString_1=8 '11 RunLoadTime '2 60 '13 StartLoadSize '1 1 '12 RumpDownTime '1 1 '16 AssistantCaption '22 Ramp Up Schedule Model '13 ScheduleModel '1 6 '11 RunLoadSize '2 30 '10 RumpUpTime '2 10 '9 TotalTime '2 71 
Schedule_1=1
From_1=00000000
To_1=00000030
LoadSize_1=1
Schedule_2=1
From_2=00000030
To_2=00000100
LoadSize_2=2
Schedule_3=1
From_3=00000100
To_3=00000130
LoadSize_3=4
Schedule_4=1
From_4=00000130
To_4=00000200
LoadSize_4=5
Schedule_5=1
From_5=00000200
To_5=00000230
LoadSize_5=7
Schedule_6=1
From_6=00000230
To_6=00000300
LoadSize_6=8
Schedule_7=1
From_7=00000300
To_7=00000330
LoadSize_7=9
Schedule_8=1
From_8=00000330
To_8=00000400
LoadSize_8=11
Schedule_9=1
From_9=00000400
To_9=00000430
LoadSize_9=12
Schedule_10=1
From_10=00000430
To_10=00000500
LoadSize_10=14
Schedule_11=1
From_11=00000500
To_11=00000530
LoadSize_11=15
Schedule_12=1
From_12=00000530
To_12=00000600
LoadSize_12=17
Schedule_13=1
From_13=00000600
To_13=00000630
LoadSize_13=18
Schedule_14=1
From_14=00000630
To_14=00000700
LoadSize_14=20
Schedule_15=1
From_15=00000700
To_15=00000730
LoadSize_15=21
Schedule_16=1
From_16=00000730
To_16=00000800
LoadSize_16=23
Schedule_17=1
From_17=00000800
To_17=00000830
LoadSize_17=24
Schedule_18=1
From_18=00000830
To_18=00000900
LoadSize_18=25
Schedule_19=1
From_19=00000900
To_19=00000930
LoadSize_19=27
Schedule_20=1
From_20=00000930
To_20=00001000
LoadSize_20=28
Schedule_21=1
From_21=00001000
To_21=00011000
LoadSize_21=30
Schedule_22=1
From_22=00011000
To_22=00011030
LoadSize_22=15
Schedule_23=1
From_23=00011030
To_23=00011100
LoadSize_23=1
[OAPI_issue_Load_Test_Mix_RTR@192.168.33.16]
StationType=PC
OperatingSystem=NT
ClientType=2
Type=Emulation
AssistentItemAAString_1=8 '11 RunLoadTime '2 60 '13 StartLoadSize '1 1 '12 RumpDownTime '1 1 '16 AssistantCaption '22 Ramp Up Schedule Model '13 ScheduleModel '1 6 '11 RunLoadSize '2 30 '10 RumpUpTime '2 10 '9 TotalTime '2 71 
Schedule_1=1
From_1=00000000
To_1=00000030
LoadSize_1=1
Schedule_2=1
From_2=00000030
To_2=00000100
LoadSize_2=2
Schedule_3=1
From_3=00000100
To_3=00000130
LoadSize_3=3
Schedule_4=1
From_4=00000130
To_4=00000200
LoadSize_4=5
Schedule_5=1
From_5=00000200
To_5=00000230
LoadSize_5=6
Schedule_6=1
From_6=00000230
To_6=00000300
LoadSize_6=8
Schedule_7=1
From_7=00000300
To_7=00000330
LoadSize_7=9
Schedule_8=1
From_8=00000330
To_8=00000400
LoadSize_8=11
Schedule_9=1
From_9=00000400
To_9=00000430
LoadSize_9=12
Schedule_10=1
From_10=00000430
To_10=00000500
LoadSize_10=14
Schedule_11=1
From_11=00000500
To_11=00000530
LoadSize_11=15
Schedule_12=1
From_12=00000530
To_12=00000600
LoadSize_12=16
Schedule_13=1
From_13=00000600
To_13=00000630
LoadSize_13=18
Schedule_14=1
From_14=00000630
To_14=00000700
LoadSize_14=19
Schedule_15=1
From_15=00000700
To_15=00000730
LoadSize_15=21
Schedule_16=1
From_16=00000730
To_16=00000800
LoadSize_16=22
Schedule_17=1
From_17=00000800
To_17=00000830
LoadSize_17=24
Schedule_18=1
From_18=00000830
To_18=00000900
LoadSize_18=25
Schedule_19=1
From_19=00000900
To_19=00000930
LoadSize_19=27
Schedule_20=1
From_20=00000930
To_20=00001000
LoadSize_20=28
Schedule_21=1
From_21=00001000
To_21=00011000
LoadSize_21=30
Schedule_22=1
From_22=00011000
To_22=00011030
LoadSize_22=15
Schedule_23=1
From_23=00011030
To_23=00011100
LoadSize_23=1
[SMVDTree]
Hosts=
[Integrated Reports]
Reports=Default Report;;
[Default Report Tree]
Generators=Total;;
[TotalDefault Report]
Type=Web
Measurements=Load Size;;Hits Per Second;;Round Time;;Throughput (Bytes Per Second);;
[Load SizeTotalDefault Report]
Measurement Types=9;;
[9Load SizeTotalDefault Report]
maxValue=100.000000
AutoAdjustedValue=-1.000000
GroupAutoAdjustedValue=-2.000000
AutoAdjust=1
[Hits Per SecondTotalDefault Report]
Measurement Types=9;;
[9Hits Per SecondTotalDefault Report]
maxValue=100.000000
AutoAdjustedValue=-1.000000
GroupAutoAdjustedValue=-2.000000
AutoAdjust=1
[Round TimeTotalDefault Report]
Measurement Types=10;;
[10Round TimeTotalDefault Report]
maxValue=100.000000
AutoAdjustedValue=-1.000000
GroupAutoAdjustedValue=-2.000000
AutoAdjust=1
[Throughput (Bytes Per Second)TotalDefault Report]
Measurement Types=9;;
[9Throughput (Bytes Per Second)TotalDefault Report]
maxValue=100.000000
AutoAdjustedValue=-1.000000
GroupAutoAdjustedValue=-2.000000
AutoAdjust=1
[AdditionalInformation]
TemplateComments=
SessionComments=
CreatedBy=
Custom1=
Custom2=
Custom3=
Subject=
TestDescription=
ResultsDescription=
Title=OAPI_issue_RTR
VersionBuild=
[NotificationManagerInfo]
TestDoneActionFromMail=
TestDoneActionToMail=
TestDoneActionSubject=
TestDoneActionMessageBody=
SendTestDoneMail=0
NotificationRulesNumber=0
